### ISSUE TITLE
autoedit.py has many errors

### ISSUE THREAD

**Issue by robgon-art** [LAION-AI/ldm-finetune#17]
First, this is a great project! I am able to create new images from text using the ongo model.

But I am getting several errors trying to run the autoedit.py script.

I am initializing my system as prescribed in the readme. But running autoedit like this throws errors.

```
!python autoedit.py --model_path ongo.pt --kl_path kl-f8.pt --bert_path bert.pt \
--edit "/content/test.png" \
--text "high quality professional pixel art" --negative "" --prefix autoedit \
--batch_size 1 --width 256 --height 256 --iterations 25 \
--starting_threshold 0.6 --ending_threshold 0.5 \
--starting_radius 5 --ending_radius 0.1 \
--seed -1 --guidance_scale 5.0 --steps 30 \
--aesthetic_rating 9 --aesthetic_weight 0.5

Traceback (most recent call last):
  File "autoedit.py", line 15, in <module>
    from guided_diffusion.predict_util import (
ImportError: cannot import name 'clip_encode_cfg' from 'guided_diffusion.predict_util'
(/content/ldm-finetune/guided_diffusion/predict_util.py)
```
I got past the first set of errors, but there are more after this.

If possible, please fix up the autoedit script to get it running again.

Cheers,
- Rob

**Comment by afiaka87** [comment]
Noted! Thanks - I'll take a look.

**Comment by afiaka87** [comment]
@robgon-art Okay I've fixed everything

**Comment by afiaka87** [comment]
@robgon-art 
Fixed here: https://github.com/LAION-AI/ldm-finetune/commit/38e0fef4de23bc273587de09766e9036f04e8b8c

**Comment by robgon-art** [comment]
Thanks! I’ll check it out…
