### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive

### ISSUE THREAD

**Issue by Limbicnation** [LAION-AI/ldm-finetune#18]
Hi I do get an error when running this scrip locally  

`python scripts/txt2img.py --prompt "a virus monster is playing guitar, oil on canvas" --ddim_eta 0.0 --n_samples 4 --n_iter 4 --scale 5.0  --ddim_steps 50`

`super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory`

**Comment by afiaka87** [comment]
@Limbicnation Not sure what script that is `txt2img.py` isn't in my repo.

**Comment by Limbicnation** [comment]
@afiaka87 Sorry I ran the following command `python sample.py --model_path erlich.pt --batch_size 6 --num_batches 6 --text "a cyberpunk girl with a scifi neuralink device on her head"`

I get the error bellow with torch.

`super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
`

I would appreciate your help! Thanks!

**Comment by afiaka87** [comment]
@Limbicnation the weights may not have finished downloading. 

Try re-downloading after removing the weights.

**Comment by Limbicnation** [comment]
@afiaka87 Thanks! I re-downloaded the weights., but now I'm get another error:

`RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.`

**Comment by Limbicnation** [comment]
It works now! I installed pytorch 1.9. Thanks very much!
