### ISSUE TITLE
What's suggested specs?

### ISSUE THREAD

**Issue by wes-kay** [LAION-AI/ldm-finetune#5]

**Comment by KnoBuddy** [comment]
Bare Minimum:
8GB VRAM 
32GB RAM
100GB HDD

The smallest iteration/step PLMS sampling can be done on less than 8gb of VRAM. Make sure you omit --clip_guidance from your prompt.

Generally 16gb of VRAM is enough, but if you want to do batch sizes greater than 1 or height/width VRAM requirements continue to go up.
